config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :beneficiaries do
      member do
        get :confirmation
        put :confirm
        post :deny_confirmation
        get :confirmation_max_shop_count
        put :confirm_max_shop_count
        post :deny_confirmation_max_shop_count
      end
    end
    resources :cities
    resources :item_categories
    resources :providers
    resources :shoppings do
      put :hard_close
      resources :shopping_items do
        collection do
          get :cart
          post :bulk_add
        end
      end
    end
    resources :shopping_items
    resources :users do
      member do
        put :activate
      end
    end
    resources :warehouse_items

    root to: "beneficiaries#index"
  end
  resource :signup_completion, only: [ :new, :create ]
  root to: redirect('/sign_in')
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
  belongs_to :provider
  belongs_to :city
  has_many :shoppings
  enum gender: [ :female, :male ]
  enum frequency: [ :weekly, :half_monthly, :monthly ]

  scope :active, -> { where(is_active: true) }

  def self.ordered
    order(is_active: :asc, last_name: :asc)
  end

  def make_active!
    update_columns(is_active: true)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_name_by_last_name
    "#{last_name} #{first_name}"
  end

  def current_shop_count
    shoppings.count
  end

  def can_shop?
    max_shop_count > current_shop_count
  end

  def family_size
    [
      family_components_count_0_1,
      family_components_count_2_5,
      family_components_count_6_12,
      family_components_count_13_18,
      family_components_count_19_30,
      family_components_count_30_65,
      family_components_count_over_65,
    ].sum
  end

  # T
  def assigned_shopping_points
    point_rank * max_shop_count
  end

  def set_shopping_points
    self.shopping_points = (max_shop_count - current_shop_count) * point_rank
  end

  # P
  def point_rank
    case family_size
    when 0 then 0
    when 1 then 80
    when 2 then 100
    when 3 then 110
    when 4 then 130
    when 5 then 140
    else
      140
    end
  end
end

app/controllers/admin/beneficiaries_controller.rb
module Admin
  class BeneficiariesController < Admin::ApplicationController
    def show
      respond_to do |format|
        object = requested_resource.as_json(methods: :current_shop_count, include: :provider)
        format.json { render json: object }
        format.html do
          page = Administrate::Page::Show.new(
            dashboard,
            requested_resource,
          )
          if params[:fragment]
            render('info', locals: { object: requested_resource }, layout: false)
          else
            render(locals: { page: page })
          end
        end
      end
    end

    def create
      resource = resource_class.new(resource_params)
      if current_user.provider?
        resource.provider = current_user.provider
        resource.city = current_user.provider.city
        resource.is_active = false
      end
      authorize_resource(resource)
      resource.set_shopping_points
      if resource.save
        AdminMailer.with(beneficiary: resource).confirm_new_beneficiary.deliver_now
        redirect_to(
          admin_beneficiaries_path,
          notice: translate_with_resource("create.success"),
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource),
        }
      end
    end

    def update
      proposed_changed = resource_params[:proposed_max_shop_count].present? && resource_params[:proposed_max_shop_count].to_i != requested_resource.proposed_max_shop_count
      if requested_resource.update(resource_params)
        requested_resource.set_shopping_points
        requested_resource.save
        if proposed_changed
          AdminMailer.
            with(beneficiary: requested_resource).
            confirm_beneficiary_proposed_max_shop_count.
            deliver_now
        end
        redirect_to(
          [namespace, requested_resource],
          notice: translate_with_resource("update.success"),
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource),
        }
      end
    end

    def confirmation
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      @beneficiary = Beneficiary.find_by(id: params[:id])
      unless @beneficiary
        redirect_to admin_beneficiaries_path, notice: 'Il beneficiario richiesto non esiste.'
      end
      if @beneficiary.is_active?
        redirect_to admin_beneficiary_path(@beneficiary), notice: 'Il beneficiario è già stato confermato.'
      end
    end

    def confirm
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      @beneficiary = Beneficiary.find(params[:id])
      @beneficiary.make_active!
      AdminMailer.with(beneficiary: @beneficiary).notify_beneficiary_confirmation.deliver_now
      redirect_to admin_beneficiary_path(@beneficiary), notice: 'Attivato!'
    end

    def deny_confirmation
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      beneficiary = Beneficiary.find(params[:id])
      beneficiary.delete
      redirect_to admin_root_path, notice: 'Beneficiario cancellato.'
    end

    def confirmation_max_shop_count
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      @beneficiary = Beneficiary.find_by(id: params[:id])
      unless @beneficiary
        redirect_to admin_beneficiaries_path, notice: 'Il beneficiario richiesto non esiste.'
      end
      if @beneficiary.proposed_max_shop_count.blank?
        redirect_to admin_beneficiary_path(@beneficiary), notice: 'Il beneficiario non ha alcuna soglia di spesa massima proposta.'
      end
    end

    def confirm_max_shop_count
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      beneficiary = Beneficiary.find(params[:id])
      beneficiary.max_shop_count += beneficiary.proposed_max_shop_count
      beneficiary.proposed_max_shop_count = nil
      SLACK_NOTIFIER.notify("[Conferma soglia massima di spesa][beneficiario ID:#{beneficiary.id}][punti spesa correnti:#{beneficiary.shopping_points}]")

      beneficiary.set_shopping_points

      beneficiary.save!
      SLACK_NOTIFIER.notify("[Conferma soglia massima di spesa][beneficiario ID:#{beneficiary.id}][punti spesa aggiornati:#{beneficiary.shopping_points}]")
      redirect_to admin_beneficiary_path(beneficiary), notice: 'Nuova soglia confermata!'
    end

    def deny_confirmation_max_shop_count
      # TODO: add authorization.
      # Only administrators can perform this action.
      # Check the definition of `AuthorizeRole`.
      beneficiary = Beneficiary.find(params[:id])
      beneficiary.proposed_max_shop_count = nil
      beneficiary.save!
      redirect_to admin_beneficiary_path(beneficiary), notice: 'Soglia negata.'
    end

    def scoped_resource
      scope = if current_user.provider?
        current_user.provider.beneficiaries
      else
        resource_class
      end
      scope.ordered
    end
    helper_method :scoped_resource

    def valid_action?(name, resource = resource_class)
      case name
      when :new then (current_user.administrator? || current_user.provider?) && super
      when :destroy then current_user.administrator? && super
      else
        super
      end
    end
  end
end

app/views/admin/beneficiaries/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/beneficiaries/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%
form_attributes = if page.resource.persisted?
  {
    url: admin_beneficiary_path(page.resource.id),
    method: :patch,
  }
else
  {
    url: admin_beneficiaries_path,
    method: :post,
  }
end
%>
<%= form_for(page.resource, url: form_attributes[:url], method: form_attributes[:method], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <% if current_user.shop? %>
      <% next unless %i[gender telephone address].include?(attribute.attribute) %>
    <% end %>
    <% next if !current_user.shop? && !current_user.administrator? && !current_user.provider? %>
    <% if current_user.provider? %>
      <% next if [:is_active].include?(attribute.attribute) %>
      <% if attribute.attribute == :provider %>
        <div class="field-unit field-unit--<%= attribute.html_class %>">
          <div class="field-unit__label">
            <%= f.label attribute.attribute %>
          </div>
          <div class="field-unit__field">
            <%= current_user.provider.name %>
          </div>
        </div>
        <% next %>
      <% end %>
      <% if attribute.attribute == :city %>
        <div class="field-unit field-unit--<%= attribute.html_class %>">
          <div class="field-unit__label">
            <%= f.label attribute.attribute %>
          </div>
          <div class="field-unit__field">
            <%= current_user.provider.city.name %>
          </div>
        </div>
        <% next %>
      <% end %>
      <% if attribute.attribute == :max_shop_count && page.resource.persisted? %>
        <div class="field-unit field-unit--<%= attribute.html_class %>">
          <div class="field-unit__label">
            <%= f.label attribute.attribute %>
          </div>
          <div class="field-unit__field">
            <%= render locals: { field: attribute }, partial: "/fields/#{attribute.class.to_s.demodulize.underscore}/show" %>
          </div>
        </div>
        <% next %>
      <% end %>
      <% next if attribute.attribute == :proposed_max_shop_count && !page.resource.persisted? %>
    <% end %>
    <% next if attribute.attribute == :shopping_points && !current_user.administrator?%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit page.resource.persisted? ? t('form.buttons.save') : t('form.buttons.create') %>
  </div>
<% end %>

app/views/admin/beneficiaries/_info.html.erb
<%= link_to "Scheda di #{object.full_name}", admin_beneficiary_path(object) %>

<% registry_attributes = %w[address gender telephone family_size] %>
<% shops_attributes = %w[point_rank assigned_shopping_points shopping_points] %>

<table>
  <thead>
    <tr>
      <th><%= t("helpers.label.beneficiary.city") %></th>
      <% registry_attributes.each do |attribute| %>
        <th>
          <%= t("helpers.label.beneficiary.#{attribute}") %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to object.city.name, admin_city_path(object.city) %></td>
      <% registry_attributes.each do |attribute| %>
        <td>
          <%= object.send(attribute) %>
        </td>
      <% end %>
    </tr>
  </tbody>

  <thead>
    <tr>
      <% shops_attributes.each do |attribute| %>
        <th>
          <%= t("helpers.label.beneficiary.#{attribute}") %>
        </th>
      <% end %>
      <th><%= t("helpers.label.beneficiary.frequency") %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% shops_attributes.each do |attribute| %>
        <td>
          <%= object.send(attribute) %>
        </td>
      <% end %>
      <td>
        <%= t("enums.#{object.frequency}") %>
      </td>
    </tr>
  </tbody>
</table>

<h2><%= t('helpers.label.beneficiary.shoppings') %></h2>
<% if object.shoppings.any? %>
  <table>
    <thead>
      <tr>
        <th># Oggetti</th>
        <th>Totale</th>
        <th>Creata il</th>
      </tr>
    </thead>
    <tbody>
      <% object.shoppings.each do |shopping| %>
        <% cart = CartForm.new(shopping_id: shopping.id) %>
        <tr>
          <td><%= cart.items_count %></td>
          <td><%= cart.price %></td>
          <td><%= shopping.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  -
<% end %>

app/views/admin/beneficiaries/confirmation.html.erb
<%= link_to 'Conferma e attiva', confirm_admin_beneficiary_path(@beneficiary), method: :put %>
<br />
<%= link_to 'Rifiuta e cancella', deny_confirmation_admin_beneficiary_path(@beneficiary), method: :post, confirm: 'Sei sicuro? Il beneficiario verrà cancellato permanentemente.' %>

app/views/admin/beneficiaries/confirmation_max_shop_count.html.erb
<%= link_to 'Conferma', confirm_max_shop_count_admin_beneficiary_path(@beneficiary), method: :put %>
<br />
<%= link_to 'Rifiuta', deny_confirmation_max_shop_count_admin_beneficiary_path(@beneficiary), method: :post, confirm: 'Sei sicuro? Il valore proposto verrà scartato.' %>

app/views/admin/beneficiaries/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <div class="index-totals">
    Totale: <%= scoped_resource.count %><br />
  </div>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: t("activerecord.models.#{page.resource_name.titleize.downcase}")
      ),
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/beneficiaries/info.html.erb
<%= render partial: 'info', locals: { object: object } %>

app/views/admin/beneficiaries/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: t("resource_attributes.#{attribute.name.parameterize.underscore.downcase}"),
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>